import { baseSchema } from "helpers/common.schema";
import { getStatusValues } from "helpers/statusLabels";
import { getReflectionFields } from "helpers/reflection.schema";

const carSchema = [
  {
    name: "status",
    label: "Status",
    type: "select",
    options: getStatusValues("cars"),
    required: true,
    section: "Main",
    order: 0,
  },

  {
    name: "vin",
    label: "VIN",
    type: "text",
    optional: true,
    placeholder: "e.g. 1HGCM82633A004352",
    maxLength: 17,
    section: "Main",
    order: 1,
  },
  {
    name: "make",
    label: "Make",
    type: "text",
    required: true,
    placeholder: "e.g. Honda",
    section: "Main",
    order: 2,
  },
  {
    name: "model",
    label: "Model",
    type: "text",
    required: true,
    placeholder: "e.g. Accord",
    section: "Main",
    order: 3,
  },
  {
    name: "year",
    label: "Year",
    type: "text",
    required: true,
    placeholder: "e.g. 2020",
    inputMode: "numeric",
    maxLength: 4,
    section: "Main",
    order: 4,
  },
  {
    name: "trim",
    label: "Trim",
    type: "text",
    optional: true,
    placeholder: "e.g. EX-L",
    section: "Details",
    order: 5,
  },
  {
    name: "bodyClass",
    label: "Body Class",
    type: "text",
    optional: true,
    placeholder: "e.g. Sedan",
    section: "Details",
    order: 6,
  },
  {
    name: "fuelType",
    label: "Fuel Type",
    type: "text",
    optional: true,
    placeholder: "e.g. Gasoline",
    section: "Details",
    order: 7,
  },
  {
    name: "engineModel",
    label: "Engine Model",
    type: "text",
    optional: true,
    placeholder: "e.g. 2.4L I4",
    section: "Details",
    order: 8,
  },
  {
    name: "engineCylinders",
    label: "Engine Cylinders",
    type: "number",
    optional: true,
    placeholder: "e.g. 4",
    inputMode: "numeric",
    section: "Details",
    order: 9,
  },
  {
    name: "displacement",
    label: "Displacement (L)",
    type: "text",
    optional: true,
    placeholder: "e.g. 2.4",
    inputMode: "decimal",
    section: "Details",
    order: 10,
  },
  {
    name: "driveType",
    label: "Drive Type",
    type: "text",
    optional: true,
    placeholder: "e.g. Front-Wheel Drive",
    section: "Details",
    order: 11,
  },
  {
    name: "transmission",
    label: "Transmission",
    type: "text",
    optional: true,
    placeholder: "e.g. Automatic",
    section: "Details",
    order: 12,
  },
  {
    name: "doors",
    label: "Doors",
    type: "number",
    optional: true,
    placeholder: "e.g. 4",
    inputMode: "numeric",
    section: "Details",
    order: 13,
  },
  {
    name: "builtIn",
    label: "Built In (Country)",
    type: "text",
    optional: true,
    placeholder: "e.g. Japan",
    section: "Details",
    order: 14,
  },
  {
    name: "startDate",
    label: "Purchase Date",
    type: "date",
    section: "Ownership",
    order: 15,
  },
  {
    name: "endDate",
    label: "Sold Date",
    type: "date",
    optional: true,
    section: "Ownership",
    order: 16,
  },
  {
    name: "purchasePrice",
    label: "Purchase Price",
    type: "number",
    isCurrency: true,
    placeholder: "$25,000",
    inputMode: "numeric",
    section: "Ownership",
    order: 17,
  },
  {
    name: "soldPrice",
    label: "Sold Price",
    type: "number",
    isCurrency: true,
    optional: true,
    placeholder: "$20,000",
    inputMode: "numeric",
    section: "Ownership",
    order: 18,
  },

  ...getReflectionFields("owned"),

  ...baseSchema.filter((field) => !["status", "notes"].includes(field.name)),
];

export default carSchema;
