export const locationSchema = [
  {
    name: "street",
    label: "Street Address",
    type: "text",
    optional: true,
    placeholder: "123 Main Street",
  },
  {
    name: "city",
    label: "City",
    type: "text",
    optional: true,
    placeholder: "e.g. Austin",
  },
  { name: "state", label: "State", type: "select", optional: true },
  {
    name: "zip",
    label: "ZIP Code",
    type: "text",
    optional: true,
    placeholder: "e.g. 90210",
    inputMode: "numeric",
    maxLength: 10,
  },
  {
    name: "country",
    label: "Country",
    type: "select",
    optional: true,
    defaultValue: "US",
  },
  { name: "lat", label: "Lat", type: "text", hidden: true },
  { name: "lng", label: "Lng", type: "text", hidden: true },
];
